CREATE TABLE IF NOT EXISTS gaming.person (
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME CHARACTER VARYING(255) NOT NULL,
    AGE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS gaming.company (
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME CHARACTER VARYING(255) NOT NULL,
    OWNER_ID BIGINT NOT NULL REFERENCES gaming.person(ID)
);

CREATE TABLE IF NOT EXISTS gaming.game (
    ID BIGINT NOT NULL PRIMARY KEY,
    TITLE CHARACTER VARYING(255) NOT NULL,
    GENRE CHARACTER VARYING(255) NOT NULL,
    RELEASE_YEAR INTEGER NOT NULL
);

CREATE TABLE iF NOT EXISTS gaming.company_game (
    company_id BIGINT REFERENCES gaming.company(id),
    game_id BIGINT REFERENCES gaming.game(id),
    PRIMARY KEY (company_id, game_id) -- unikaluri wyvliebi mxolod
);

CREATE SEQUENCE iF NOT EXISTS gaming.person_seq INCREMENT 1
START 1000;

CREATE SEQUENCE iF NOT EXISTS gaming.game_seq INCREMENT 1
START 1000;

CREATE SEQUENCE iF NOT EXISTS gaming.company_seq INCREMENT 1
START 1000;